// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-rmG8PSEqWDg-v5wGgotgGrzmjRs_W7s',
    appId: '1:403485156808:web:74e7376b32ae67c3d30cfd',
    messagingSenderId: '403485156808',
    projectId: 'globego-3ad3a',
    authDomain: 'globego-3ad3a.firebaseapp.com',
    storageBucket: 'globego-3ad3a.firebasestorage.app',
    measurementId: 'G-BV5SDYDV3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDghS7B3h3pGvEPdl_jkCZduQW0Kyhu54c',
    appId: '1:403485156808:android:d0777f7860e2a15cd30cfd',
    messagingSenderId: '403485156808',
    projectId: 'globego-3ad3a',
    storageBucket: 'globego-3ad3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa_IiwKtZJILU-wt9v2yc9UqK7v7MX9pg',
    appId: '1:403485156808:ios:13887fabce507b25d30cfd',
    messagingSenderId: '403485156808',
    projectId: 'globego-3ad3a',
    storageBucket: 'globego-3ad3a.firebasestorage.app',
    iosBundleId: 'com.example.yeniProjem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa_IiwKtZJILU-wt9v2yc9UqK7v7MX9pg',
    appId: '1:403485156808:ios:13887fabce507b25d30cfd',
    messagingSenderId: '403485156808',
    projectId: 'globego-3ad3a',
    storageBucket: 'globego-3ad3a.firebasestorage.app',
    iosBundleId: 'com.example.yeniProjem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-rmG8PSEqWDg-v5wGgotgGrzmjRs_W7s',
    appId: '1:403485156808:web:48a0ac19d6f62bbed30cfd',
    messagingSenderId: '403485156808',
    projectId: 'globego-3ad3a',
    authDomain: 'globego-3ad3a.firebaseapp.com',
    storageBucket: 'globego-3ad3a.firebasestorage.app',
    measurementId: 'G-B7QMBMPPPZ',
  );
}
